### ISSUE TITLE
Q_Where is the "data_to_be_used_final" comes from

### ISSUE THREAD

**Issue by Ciao-Wen-Chen** [VincentAuriau/Tennis-Prediction#1]
Dear author, 

I am a student for uni of Glasgow.
Thanks for providing this excellent code for us to learn,
However, when I trace the code I can't understand where the "data_to_be_used_final", the input file for Prediction.py, comes from.
From my understanding, it might be a collection of the whole used data set.  
Can you tell me how you produced this file?

Sincerely,

**Comment by VincentAuriau** [comment]
Hello,
I'm closing the issue since the code has changed.
Here is an example to load data: https://github.com/VincentAuriau/Tennis-Prediction/blob/master/examples/data_loading.py

Feel free to open another issue if needed.
Thank you,

**Comment by Ciao-Wen-Chen** [comment]
Thanks a lot!
Best,
Charlotte 

Sent from Yahoo Mail for iPhone


On Saturday, February 11, 2023, 4:45 pm, VincentAuriau ***@***.***> wrote:




Hello,
I'm closing the issue since the code has changed.
Here is an example to load data: https://github.com/VincentAuriau/Tennis-Prediction/blob/master/examples/data_loading.py

Feel free to open another issue if needed.
Thank you,
